language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: NGiGnomV1qmp30jLdSCBL5mA2FNSJVvrI6voCH2tyFjJ8yczrHlibVba2L6mOeKwLDDeoc9iVJYIcaAgEtP56EDh9KINBiMdPMkQgajur6lnx5yG7d79+w9nfDzlpWf/QgyYKutSdCMABv3lrLCgZHZAHZ25QLYTInJI/noE6V0w1WMv74rtdiO+DUT5Gzic5mnHHsb5BKjhV+J342FXAkLtmlsHBGv6DHJheobT1Zkm2qpSY9+8Uvag2vUfyDy7AuxOZUGDu/bVgyQvgLepu21UrTPoCdmlCKsobHjVMi+4scXRkEB1I4wOeFkVfQjV0t0pls86ioQTO1NytqoOB6iAFdq1ZGTXduxMPiFlvFr9QmCutLpgKI9tVhaf3JusHjixVLWOMSJ8sASGFwIIq/a4GfmytO+nTXwGHm4WNIX34WQ6gyu5ljY4pss1lo/dD74S0iKqdO9Bt8npdBIRzMXdqyBiSS2U+IEq7u3zHcv4Zm2+J8u2oSFhNHkAxM+u7ww90c949iy6834AfumahWkpIkQKmE99N+EsLhCZjexITrp2WQgmxErTdd4ZBSwlFSoa9B4KIHnrs2vFiexOPe+CRAIppy6PrZY5sHecCV8KykDrstt0H/kA0FiRoXsO/j4zo/d+ywTjWgzoTOOl4UibZksTUY8x8nCUzmCMRlo=
