language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: YEyS14uLKEKo/LrQPig3vvQyVlv9RtJA1wEOmkozOSLokOrr9RN7VawB4gwO6beRJNH96FVXRsvtWY0NCJox+ep1Bf/rdvx+VqS0csX7EhdsYbbjfXKEYUoboHej85UI0MSTAJC+yVSwutJN/0fVsBaffzOkO+X3Xh/o6oe09XMCY9ya0o7KRu3C9SCJcjueShMdr69coeQ4Bssob2RpqcakjnjmMJr+HK8zw9W6C6vnm7LeYhrCi6OJLLVCxTRXwFwxvdN8/9Rq6Iu2UbB7KpGBGnH9d5VuJ+fodziHTDNCGydF/E+UOk37ZrmYwUG3PblMUKyF2uI4w3ga7z/iykrRkH8K/t3AIibhdUPyXuXgU9khQlItn6kJOsJfpQn8e4UJGX5pWAdSuVHYZG+ECeBcvLyWxc7MgPnemo6mUYxheYkZum16Ya2kz6AjDPPAYFQFjnyHZ5fioURy8lSiNvcrX8sV1GmMRikmEWDB0Htr1d8tNY6pCMnzwVK5i9JZSul2w/2Gw6jCJR2HG3ZFqcTvIqgzAZVuHxfuLY1mMr+y2rOUbnYPDE6iaXIcpWfuRb4CO7ppxseOfUHFfPzDy/ku+jAQEBkUcRw2u4zcopOM2PhQ5RNLoShMJRmJVTfl0OMW37uMyYp74HHOQ0SqZNbgZoqE71z/qcABS8XvMlk=
#  app: osmos-09-2016
#  on:
#    repo: sergey90x/osmos-09-2016